// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManager.Models;

#nullable disable

namespace StudentManager.Migrations
{
    [DbContext(typeof(StudentManagerDbContext))]
    [Migration("20231019043408_Initial2")]
    partial class Initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManager.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "One"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Two"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Three"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Four"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Five"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Six"
                        });
                });

            modelBuilder.Entity("StudentManager.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("StudentManager.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("GenderId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be9d07ea-fe41-4d88-b696-9f463a0c8c12"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("b0701f97-5ed5-4d19-87a7-bcc2e4dd7e22"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("34139f43-4145-4936-a3b3-5101105e469c"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("86b15478-07d2-4221-a350-83527120679b"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("5f1fc5d1-f6e7-41a4-8094-5f338d21ffcc"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("e1fb2afb-50b2-4092-b6d0-faef732be793"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("54a4a838-0b1f-4312-851f-464725eab864"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("e5699251-4ebd-451b-8494-a1413371fc74"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("78df73d1-8e89-464a-b841-e85c1947b081"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("ffa73ab2-b560-434d-ab9c-a83268d4c069"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("9ba81591-e337-41e5-b69e-b0d80736eab1"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("bd4a24da-cb3a-4d98-a5c8-524614ee1424"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("b4e742c4-cb6f-47ae-a38d-22875f9fbde6"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("4fe71e88-8564-41b9-bbf4-6883b60c2091"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("a773e4f5-b93e-492a-b6ce-8a5e9bf23fee"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("3f21b8ae-3ba2-4774-9c4c-74d4714d8415"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("c3629de2-5f05-4d6b-9db1-3208f6f23ce2"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("6f0bc57e-b867-4f43-93f0-d07662821b56"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("629cfff0-bd49-4bed-967a-bbaaeccb3bcf"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("ec1ae716-896d-48b4-84fe-d761ef683c65"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("2f087751-de5e-465d-b380-bd793ac2771c"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("1017a5f1-21d0-4895-b066-85a163f9ac02"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("0fa4bdac-4668-456e-b27c-69c732f1ea42"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("d6f8685d-8f06-4428-b172-606388e41387"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("b2db1535-b5ff-42b0-bef0-2092abe2354d"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("46a92555-ab71-43b1-a4db-000ceb7678ed"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("48538e9c-c4c0-4a28-b8ce-2b3b4cab09ef"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("ca28e9e7-f8f0-48c5-8e02-09cc0532aba1"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("2bae9c91-f7cf-47e3-8a79-4677131bfad0"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("3f5f00a8-1cc9-419a-93f1-556a8ac31afc"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("f1d7e335-a70e-43c0-8390-fc4eb320459d"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("b9961793-1ea0-43c8-a7fb-b7204ab53284"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("c059311a-b5c5-4e6e-be0d-574dce0ff703"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("9a8f1371-6591-473a-aa5f-6f88eac824e7"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("76620eaa-73b9-4469-be31-eb90bdd5fc3a"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("af6b1a10-fddd-4b34-bbf2-f83bcfcec926"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("5124a96d-6111-4f1f-884d-7d35f329e1e7"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("819602a5-762c-4490-9ab2-f11b48e13406"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("2eb91f7e-a349-4830-ab7d-b243a09e38b9"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("f6e94d30-eb52-4e33-ad58-664b286cc4e0"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("f650413f-1d10-46aa-ada1-1248a320318e"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("5c83c4a3-f329-4639-8193-b1db15c37aee"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("837438ae-a404-4159-9470-0ae5e9a7a65d"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("7d259275-7290-43bc-a8f9-1b3e112881d0"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("5cdd9a8f-bab8-409e-a4e7-fc29014961a6"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("fd08e3a2-b801-44d3-8204-328ab6bec09c"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("7858b4dc-fc9a-45d8-8f2a-c10fd9f7d443"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("fc766599-0842-4b71-8b0a-e8492ec69142"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("ba0fbcac-2a31-4ecf-b985-144fdc6749fb"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("51f40884-b8b7-40c7-b4f2-046f7b105f5c"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("e525f3d1-3931-44f6-8db5-c58118734dfe"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("1c1073d6-528e-4070-acd6-8814f99efc3b"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("c426d19c-f866-4b56-97e9-6af03b2a69f1"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("c83090a5-4f05-403a-aa19-9228515dd6b4"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("02bf8ebd-1972-40e0-ae14-e8d906d510fe"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("85c65b3b-1dd8-4565-a6a8-ee64b2b274af"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("25e37e4e-e4c8-4b2f-b811-9376f29d6f1c"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("5ffafee4-19a3-4286-be0f-72aa9dc5b3d9"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("96bdb686-917d-4b48-9d9d-2d6214cc4bd1"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("29af959e-9f94-4378-8c38-101046689b71"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("0e7494e0-61d8-4a81-a59a-4a231b9a87ff"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("a4bf4992-4c21-4c5b-9626-74885fabef07"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("e8c6bfe8-489f-4770-9323-d65f9e1aa258"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("3f4b7f69-ddc9-4a48-a3fc-40f758c192a9"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("acd32f8e-4978-4772-9c0b-7d4ec0699c07"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("ca5d31ad-a40f-4d3a-81d9-0513876574ec"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("0d12e0c4-f466-4b28-bcca-6e77e52cce39"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("454d124f-f516-4f45-9e18-18296fa55121"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("4120798f-24d9-4c3c-a9fa-0e464533b1fd"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("b5d92dbe-2de2-408f-ad17-ec501a77e194"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("1936e0f6-2e2e-4877-af71-e5b6d02dfc4d"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("b141dd96-6420-424f-9bd0-0c63a885c680"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("b62f89a5-8884-46f2-b5b0-face0a111416"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("c9a1c3a7-99a8-4dbf-bc74-8ca98f712bd0"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("0afea8eb-84d8-4cff-be22-cf791988ff9f"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("34f55909-62ad-44d1-9972-a5925ad3ef64"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("7db9007a-1fc9-4035-8c74-cfc41aca6c6a"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("9f164ba2-b77a-4923-8990-0dc4e1ac4c22"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("deb81ba0-db1b-49b6-9d7f-925adb552241"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("25e87f86-9200-4db9-986f-77682b1b671e"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        });
                });

            modelBuilder.Entity("StudentManager.Models.Student", b =>
                {
                    b.HasOne("StudentManager.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManager.Models.Gender", "Gender")
                        .WithMany("Students")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("StudentManager.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentManager.Models.Gender", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
