// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManager.Models;

#nullable disable

namespace StudentManager.Migrations
{
    [DbContext(typeof(StudentManagerDbContext))]
    [Migration("20230913172522_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManager.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "One"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Two"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Three"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Four"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Five"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Six"
                        });
                });

            modelBuilder.Entity("StudentManager.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("StudentManager.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("GenderId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7091cdf1-fcf3-48c1-a16d-0ad208572367"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("8fd15520-84b7-4094-913a-8210769fb4fc"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("30338284-1163-49ed-a7a0-3ff928c8d247"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("eecd6013-e4f4-4fab-b14d-5204160c46be"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("f5cf238a-cbe3-407e-a51a-8742f9bcf2a3"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("86a754ad-bf76-4833-ab14-209ac3237307"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("b97bdf1f-6a2f-4e32-83df-dbfb4b4603d7"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("b1559dad-e746-4783-b656-e8e0da3f6346"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("e81a3276-0a78-41b5-aaf7-6cebad0c761a"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("898f0f62-36a6-413b-b6e2-4e5a69a64ff6"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("a4cc24b1-5a3e-4ad6-ae9d-a39a6fafadf3"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("8d5dd87e-3629-42b8-98cd-8ee25e5fe8a0"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("092cd5e9-a4ac-4985-9f06-3315e347c46d"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("7925d26b-1474-49f1-9d13-1e4371475f12"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("864dbfa5-0be9-4662-b2bc-0dc7f47aab18"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("cc0d45d1-d40c-49c3-b455-035836563395"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("29a8978a-19e4-46d1-a78d-bfdfb6abd76f"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("36b15cd9-f89b-4eed-9ea7-f7762b7987fe"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("ba0cbb8b-2a7f-460b-b6c5-abffaf9b691f"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("df78669b-a9fa-440a-bc1e-557f15a64fc4"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("622c269a-9a2d-4321-b9d2-e2836b28bcae"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("2dd00934-93fe-4a25-ad0b-c34754577a89"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("7c6c2540-6ee8-4517-8dbb-f46176b609d0"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("f9cfea73-8402-482d-8f9b-8c37d6a8cc49"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("ec581a1f-1994-43be-a9d1-9d59c46f9c80"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("1fff6898-69dc-4c62-ab7a-7059913406c2"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("490a27a8-bc07-4fd6-8894-873aa434cae8"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("041d36e4-7e03-43a1-a3e1-044d0104e32b"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("c835cefe-679d-4d5a-8bb2-2b5bf5c9a43b"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("f3aa01ff-34d2-40b1-a302-49278b610649"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("b6f8d8cd-7e22-4b10-ae39-88f3b87fe319"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("3ffc986c-7ac0-4da4-a3ff-4f689c532f70"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("0913e802-96bc-4223-880f-a549d93aee75"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("eeeab530-bc97-4bf4-9463-6142575c3b83"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("be0ac64e-5193-4b4a-a167-37c51a0d6c31"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("7456c206-30ad-41b5-b3bd-ca1b5d737796"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("0a629715-0828-42e8-b7a4-0acb9c58dbf8"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("4627cdda-6498-4d1a-9c06-149bfc5d1414"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("11e301e0-31bd-430f-9e72-fc91f878adc1"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("3e59c093-65f1-49e1-8922-34fd823c42cf"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("a462702b-3080-4296-9ba9-43febb8557c1"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("3f688c1f-044e-48fd-a0bd-565559dcc798"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("e8a6e755-0e54-4e07-a76a-0545250da1a4"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("dee31b64-e576-475b-ac9c-a7ccb3df2969"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("f49f0e83-e1d8-4f75-9ded-1c66b75505a6"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("de95e2c8-58e5-432b-ab55-b2ef82768a03"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("3c92ea87-4e93-4032-8bc6-635b7f0e3f77"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("ac3be9a7-2fce-430c-a7ba-5e044e586bb1"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("7de92eca-1603-4cb4-a27e-fbd91a380fed"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("a8e62d10-c2fe-4119-86d4-9844013d970f"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("6ceeadfb-e04c-4cf7-b116-6e7753717d75"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("b50c8472-a8d8-4147-9658-fe62d0090bb6"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("00e6c5e2-6a1d-47af-9b99-30429969ae22"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("40404935-088c-4c46-a9a0-361eccace7c4"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("5bb7b4a2-a1f5-433e-8bde-ff67ea2f7c0a"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("59b5f8e2-38fd-4330-80bf-3f80a2b9fc3f"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("5424cc7b-2258-4ea8-be24-002453651e32"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("42bc6b41-0f6b-4be6-a8d4-3c179155ce6d"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("a47b8a4c-eb9b-4757-a3a7-d7f3f3e7e5f9"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("d105cb46-98f9-4e87-94db-9e45ce0d26ec"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("dc9b8562-c7b8-4365-a16c-afcfaf215e07"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("7dc3e1a7-1926-4867-8325-bec697faa84e"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("e713a4c2-b77c-4051-917b-dc6d8f01cb3e"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("8900cdac-5205-494f-a96e-630b63025c87"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("51478f19-0de2-4864-aa12-48b2237ed57e"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("73bc7841-724b-4dfe-ba7d-ae01ff4bda52"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("c7b7ddf8-11c7-4ea3-bfa7-14607a3cc788"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("1bfb4dcc-9a18-41f8-909a-31597114625e"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("c4d347cf-ad91-4a0c-a4a0-da7b7cbebb28"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("e7117431-7a6c-4370-8360-ef361a9d5db1"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("65837564-6067-4775-8fe3-0226ac8d0b81"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("bafb8905-92f0-4bfa-a217-044d6d3dc816"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("d62dea9a-b1f8-4099-8d60-a3fea409be6c"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("52b06b93-e340-4cec-a10f-d1f155b05796"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("4af7d7ec-78db-447d-be31-bf7a11cce1bc"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("2a46bf34-3f3c-425f-8035-972b129b7368"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("e03f5bf6-fc0b-4255-a009-d30f22bae224"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("7ce040fa-0e23-48ce-86ce-f62335cf3b70"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("d25f747d-1300-47c8-bb9b-e7e4b32ced26"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("05b3091b-2715-40bc-8759-fd70ab5d1712"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        });
                });

            modelBuilder.Entity("StudentManager.Models.Student", b =>
                {
                    b.HasOne("StudentManager.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManager.Models.Gender", "Gender")
                        .WithMany("Students")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("StudentManager.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentManager.Models.Gender", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
