// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManager.Models;

#nullable disable

namespace StudentManager.Migrations
{
    [DbContext(typeof(StudentManagerDbContext))]
    partial class StudentManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManager.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "One"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Two"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Three"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Four"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Five"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Six"
                        });
                });

            modelBuilder.Entity("StudentManager.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("StudentManager.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("GenderId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33b1c80e-0099-47fe-be52-e2bf454da00c"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("4db85fdd-144f-4821-b8b9-89c4093c5878"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("628fd6e0-6a98-4d70-aa47-1c6d4fbe56da"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("c66936d3-ff07-4312-bac6-ea76e01a6c3e"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("23374c6c-50b8-4100-81d1-6010a8902248"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("c9ac8ed8-0b2e-4ed1-8fbd-5db2c4e001bc"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("f2728601-3b6a-4361-ad69-a2fb9994bc65"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("d818f6a1-93ec-4519-bc82-46a0d733e788"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("0d6c3c6d-2c00-49a4-a58f-73e7bd621ef7"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("4452f388-8840-495f-b811-782868c1c63b"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("ec85897a-2faa-490c-9cf8-6d3c8a484e54"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("372e21b7-f8a5-49a7-8249-29b509d0d5d4"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("ff94e043-f6cc-4d17-bbb5-31e30fc52455"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("dade525b-8789-4a8e-ae13-81d8fc163aea"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("84baadb2-06fe-496c-9556-e552937ff6d1"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("371580c3-e91b-4bfe-a103-26b1c3c93b0f"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("7d17a657-c257-448a-98a4-3bea05c4ff43"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("14a62a0d-42bf-4adb-bdc4-32ac70d3b02d"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("e2191d15-52b2-446f-9257-d2a42edd64f9"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("c1bc3bc6-4b04-44ab-b811-21877596217e"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("70cad858-53e9-4b57-84d6-87e163ad2699"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("e5304c8e-acd5-43ab-9744-6734baa7fcc9"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("2d3114cf-25c8-4047-9300-f2ce16d4bbf3"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("70345d22-5efd-4af2-83a4-01974609fa09"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("16fc6776-4b04-4a0a-8a9a-5a01fbd465e4"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("f33057a9-d0fa-425a-beb9-7a11f282432e"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("01068940-d8b6-46bb-9ebb-af8ff8b5a1af"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("92fc6a80-7b3b-49f8-b8fa-a5ed8078119f"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("f0a6b098-9676-492b-a35c-3046509ff095"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("a17c13b7-e83c-4b86-951b-742ce32a4691"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("2718d06b-30a3-4aca-9dc9-6158eff90121"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("3e8d3335-778a-494d-8488-8ed043948be9"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("b5257f29-4b2a-4345-aba3-c6b506a6354f"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("847b2a87-c7f8-4f24-923d-daf29b5bcd28"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("e76c7194-9656-4c3e-9077-b58fe8bdbd78"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("053460f2-bf9b-4980-87bd-7727a75205e7"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("6d193cde-a028-4aae-adb2-c6156f7f2512"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("59fffccb-8d21-4f2f-8737-546f0dcf3dcf"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("8258de8d-68d0-487d-9b9a-c57affaf73b4"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("53f51358-f770-4b11-b1e9-b31232509d29"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("30495548-8c0a-430b-a213-73d9050e861f"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("cb09f73f-1883-47ad-af80-6a449a05335f"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("813bae38-6f63-4e1d-9a99-f051505d235e"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("59925574-50b3-4ea3-887b-692e5a6a0f1d"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("87c38b58-a6e2-4e88-af77-0243b72b0919"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("e0aa1218-c691-4c68-a927-ffefc4e458e1"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("8d43aebe-c993-488a-841f-787dbaf8a09c"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("35047547-697d-45a5-81fe-d7a8d0915483"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("1798de01-534c-4272-8667-8a89df61fce8"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("227624eb-65ff-4742-ad5f-5c99e23c2ee3"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("d90523be-123e-4acd-a4f1-37d6795cf43c"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("994c99b0-187d-402d-9800-7db241c744d3"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("4ec373af-990c-470d-b2f3-fd5955f278a2"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("b7c816cb-1b02-42d4-8c8c-9501ac730b10"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("fa276126-a39d-43cd-8198-859e8b40552c"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("07c713e5-78ba-4d5b-ae55-6f570ffd58c1"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("33ee32bd-1efe-4c21-990c-4b85279e0a62"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("fd340fad-ffa8-4e4b-9844-b42b31474fb9"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("a3d213a4-1628-4a2b-8642-10aa84c645e7"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("b8fa667c-ab83-49d0-a2ff-f0e344c2a904"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("dcc395eb-af10-4e23-b6bc-fc14d1e9b614"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("23df7009-8d83-4e5e-b01a-aca42d686e00"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("7a2bb975-1d61-4f73-98ba-527a7aed2418"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("70c6d749-3b19-41ef-b5cb-2ad3d7111ec4"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("2d1372b5-e9f2-4ffd-98c6-67613e5aa594"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("49f57ccd-cd79-4290-8955-c0cf13e5564b"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("9cafd9cd-dc7f-4173-bb1f-595ffbcc4c07"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("4c7f621a-4984-492b-8d23-f13b92f6a125"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("ba189b2f-d7cf-4327-9bce-6b5f5f741c34"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("3025a811-befc-439e-912c-da894353f5d1"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("02ef70ef-1044-4537-bd69-cb745a2ccb4c"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("e102e9d7-5590-4379-9ea5-9335d13e6fb4"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("71d9a5cc-2af5-4fa9-a3ad-3ba62a10c670"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("4b9efe91-d9fc-4af9-8189-e0a74335cd8c"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("be2eb559-5db8-44fe-847f-e4b7ba53225f"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("3b144024-a74c-4a34-af09-37c403cfa76e"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        },
                        new
                        {
                            Id = new Guid("89fc0f96-3f2a-469a-8e0b-f246c6c7ff13"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 1,
                            Name = "Shuvo Islam"
                        },
                        new
                        {
                            Id = new Guid("f6bbe8b6-147b-48ff-9fb4-82ebcfa6b9fc"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Shawon Sheikh"
                        },
                        new
                        {
                            Id = new Guid("3a13d75e-5f09-4883-9f41-9ba9e8bd56da"),
                            ClassId = 3,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1995, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 3,
                            Name = "Sahabuddin Sheikh"
                        },
                        new
                        {
                            Id = new Guid("9a01ae0f-6a28-49f6-8a19-1630045707c1"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            DOB = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderId = 2,
                            Name = "Shaiful Sheikh"
                        });
                });

            modelBuilder.Entity("StudentManager.Models.Student", b =>
                {
                    b.HasOne("StudentManager.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManager.Models.Gender", "Gender")
                        .WithMany("Students")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("StudentManager.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentManager.Models.Gender", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
